name: cisTEM CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        compiler: [icpc,gcc,clang]
        include:
          - compiler: icpc
            cxx: icpc
            cc: icc
            staticmode: "--enable-staticmode --enable-openmp"
          - compiler: gcc
            cxx: g++
            cc: gcc
            staticmode: "--enable-staticmode --enable-openmp"
          - compiler: clang
            cxx: clang++
            cc: clang
            staticmode: ""
          
    runs-on: ubuntu-latest
    container: cistemdashorg/cistem_build_env:ci_${{ matrix.compiler }}
    outputs:
      version: ${{ steps.configure.outputs.version }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: regenerate_project
      run: ./regenerate_project.b

    - name: configure
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        mkdir -p build/${{ matrix.compiler }} 
        cd build/${{ matrix.compiler }} 
        echo $CC
        echo $CXX
        # FIXME: we should be able to get rid of enable-samples as these are default
        ../../configure  --enable-experimental ${{matrix.staticmode}} --with-wx-config=wx-config  --enable-samples 
        VERSION=$(cat config.log | grep CISTEM_VERSION_TEXT | cut -d' ' -f3 | tr -d '"')
        echo "::set-output name=version::$VERSION" 
    - uses: ammaraskar/gcc-problem-matcher@master
    - name: make 
      run: |
        cd build/${{ matrix.compiler }}
        make -j2
        cp ../../scripts/testing/test_and_benchmark.sh src/
    - name: clean up
      run: |
        cd build/${{ matrix.compiler }}
        rm -r src/core
        rm -r src/gui
        rm -r src/programs
    - name: Create binary artifact
      uses: actions/upload-artifact@v2
      with: 
        name: cistem_binaries_${{ matrix.compiler }}
        path: build/${{ matrix.compiler }}/src

  console_test:
    strategy:
      fail-fast: true
      matrix:
        compiler: [icpc,gcc,clang]
    name: Console test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: cistem_binaries_${{ matrix.compiler }}
    # - name: Install fftw3
    #   if: ${{ matrix.compiler=='gcc' || matrix.compiler=='clang' }}
    #   run: sudo apt-get install -y libfftw3-dev
    - name: Fix permissions
      run: chmod +x *
    - name: test console_test
      continue-on-error: false
      run: ./console_test 
    - name: run benchmark
      run: ./test_and_benchmark.sh ./
    - name: Create image artifact
      uses: actions/upload-artifact@v2
      with: 
        name: test_images
        path: /tmp/*.mrc

  samples_functional_testing:
    strategy:
      fail-fast: true
      matrix:
        compiler: [icpc,gcc,clang]
    name: Samples functional testing
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: cistem_binaries_${{ matrix.compiler }}
    # - name: Install fftw3
    #   if: ${{ matrix.compiler=='gcc' || matrix.compiler=='clang' }}
    #   run: sudo apt-get install -y libfftw3-dev 
    - name: test samples_functional_testing
      continue-on-error: false
      run: |
        chmod +x samples_functional_testing
        ./samples_functional_testing

    # TODO add unit test runner after next PR

